In [2]:
# CREACIÓN DE UN ARREGLO A PARTIR DE UNA LISTA

import numpy as np

lista1=[1,2,3,4,5]
arreglo1= np.array(lista1)
arreglo1

array([1, 2, 3, 4, 5])

In [4]:
type(arreglo1)

numpy.ndarray

In [8]:
# CREACIÓN DE UN ARREGLO A PARTIR DE UNA LISTA DE LISTAS

lista2=[[1,2,3],[4,5,6],[7,8,9]]
arreglo2= np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# LAS LISTAS PUEDEN CONTENER DIVERSOS TIPOS DE DATOS

lista=["a", True, 1]
lista

['a', True, 1]

In [12]:
# LOS ARREGLOS SÓLO PUEDEN TENER UN MISMO TIPO DE DATOS
# USAN MENOS ESPACIO EN MEMORIA

arreglo= np.array(lista)
arreglo

array(['a', 'True', '1'], dtype='<U11')

In [30]:
# CREACIÓN DE ARREGLOS CON CEROS

arreglo4= np.zeros((5,4))
arreglo4

array([[1, 2],
       [5, 7]])

In [34]:
arreglo4.shape

(5, 4)

In [16]:
# CREACIÓN DE UN ARREGLO CON NÚMEROS ALEATORIOS UNIFORMES ENTRE 0 Y 1

np.random.random((3,2))

array([[0.92466471, 0.91693596],
       [0.57735873, 0.95193174],
       [0.85162572, 0.73223595]])

In [20]:
# CREACIÓN DE ARREGLOS EN UN RANGO

np.arange(-2,7)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [26]:
# ARREGLO MULTIDIMENSIONAL

arreglo1= np.array([[1,2],[5,7]])
arreglo2= np.array([[8,9],[5,7]])
arreglo3= np.array([[1,2],[5,7]])

arreglo_3D=np.array([arreglo1,arreglo2,arreglo3])
arreglo_3D

array([[[1, 2],
        [5, 7]],

       [[8, 9],
        [5, 7]],

       [[1, 2],
        [5, 7]]])

In [36]:
# CONVERSIÓN DE ARREGLO MULTIDIMENSIONAL A UNIDIMENSIONAL

lista2=[[1,2,3],
        [4,5,6],
        [7,8,9]]
arreglo2= np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arreglo2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# CAMBIO DE DIMENSIÓN DE UN ARREGLO

arreglo=np.array([[1,2],
                  [3,4],
                  [5,6]])
arreglo.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
# CAMBIO DE TIPO DE ARREGLO

arreglo_booleano=np.array([[True,False]],dtype=np.bool_)
arreglo_booleano.dtype

dtype('bool')

In [46]:
arreglo= arreglo_booleano.astype(np.int32)
arreglo.dtype

dtype('int32')

In [59]:
# EJERCICIO DE ACCIDENTES

Lista4=[[0,1,1],[1,0,1],[1,3,2],[2,2,0]]
accidentes= np.array(Lista4)
accidentes

array([[0, 1, 1],
       [1, 0, 1],
       [1, 3, 2],
       [2, 2, 0]])

In [61]:
# SUMA DE ACCIDENTES

accidentes.sum()

14

In [65]:
# ACCIDENTES POR AREA

accid_areas=accidentes.sum(axis=0)
accid_areas

array([4, 6, 4])

In [69]:
print("Los accidente del area 1 son: ",accid_areas[0])
print("Los accidente del area 2 son: ",accid_areas[1])
print("Los accidente del area 2 son: ",accid_areas[2])

Los accidente del area 1 son:  4
Los accidente del area 2 son:  6
Los accidente del area 2 son:  4


In [71]:
# ACCIDENTES POR AREA

accid_anios=accidentes.sum(axis=1)
accid_anios

array([2, 2, 6, 4])

In [73]:
# CONSERVACIÓN DE DIMENSIONES

accid_areas=accidentes.sum(axis=1, keepdims=True)
accid_areas

array([[2],
       [2],
       [6],
       [4]])

In [75]:
# Máximo y Mínimo de accidentes

Máximo= accidentes.max()
Mínimo= accidentes.min()

print( f" El máximo de accidentes es {Máximo}")
print( f" El mínimo de accidentes es {Mínimo}")


 El máximo de accidentes es 3
 El mínimo de accidentes es 0


In [79]:
# Promedio

Promedio= accidentes.mean()
Promedio

1.1666666666666667

In [81]:
# SUMA DE ARREGLO MÁS 3 EN CADA DATO

arreglo= np.array([[1,2,3],
                   [4,5,6]])
dimensiones= arreglo.shape

print(dimensiones[0]) #Renglones
print(dimensiones[1]) # Columnas
print( arreglo[0][0])

2
3
1


In [87]:
# HACERLO CON PYTHON

import time
inicio= time.time()

arreglo_final=np.zeros((2,3))

for renglon in range(dimensiones[0]):
    for columna in range(dimensiones[1]):
        arreglo_final[renglon][columna]=arreglo[renglon][columna]+3

print(arreglo_final)
fin=time.time()
print("Tiempo total de ejeución (segs.)", fin-inicio)

[[4. 5. 6.]
 [7. 8. 9.]]
Tiempo total de ejeución (segs.) 0.0009999275207519531


In [93]:
# HACERLO CON OPERACIONES VECTORIZADAS

import time
inicio= time.time()
arreglo_final= arreglo+3
print(arreglo_final)
fin=time.time()
print(" tiempo total de ejecución (segs.)", fin-inicio)

[[4 5 6]
 [7 8 9]]
 tiempo total de ejecución (segs.) 0.0009982585906982422


In [95]:
# BROADCASTING
# MULTIPLICACIÓN CON BROADCASTING

arreglo= np.array([[1,2,3],
                   [4,5,6]])
arreglo_prod= arreglo*3
arreglo_prod

array([[ 3,  6,  9],
       [12, 15, 18]])

In [97]:
# ADICIÓN DE 2 ARREGLOS

arreglo1= np.array([[1,2,3],
                   [4,5,6]])

arreglo2= np.array([[7,8,9],
                   [10,11,12]])

arreglo3= arreglo1+ arreglo2

arreglo3

array([[ 8, 10, 12],
       [14, 16, 18]])

In [99]:
# EVALUACIÓN DE CONDICIONES

arreglo1= np.array([[1,2,3],
                   [4,5,6]])

arreglo1>2

array([[False, False,  True],
       [ True,  True,  True]])

In [107]:
# VECTORIZAR LEN


arreglo= np.array(["numpy", "manejo" , "vectorización"])

len_vectorizada=np.vectorize(len)
len_vectorizada(arreglo)>5

array([False,  True,  True])

In [109]:
# BROADCASTING DE RENGLONES

arreglo= np.arange(10).reshape((2,5))
arreglo

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [113]:
arreglo+ np.array([0,1,2,3,4])

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [115]:
# BROADCASTING EN COLUMNAS

arreglo= np.arange(10).reshape((2,5))
arreglo+np.array([0,1]).reshape((2,1))

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [117]:
# VOLTEO A UN ARREGLO

arreglo= np.array([[1.1,1.2,1.3],
                   [2.1,2.2,2.3],
                   [4.1,4.2,4.3]])
np.flip(arreglo)

array([[4.3, 4.2, 4.1],
       [2.3, 2.2, 2.1],
       [1.3, 1.2, 1.1]])

In [119]:
# TRANSPOSICIÓN DE UN ARREGLO 

arreglo= np.array([[1.1,1.2,1.3],
                   [2.1,2.2,2.3],
                   [4.1,4.2,4.3]])
np.transpose(arreglo)

array([[1.1, 2.1, 4.1],
       [1.2, 2.2, 4.2],
       [1.3, 2.3, 4.3]])

In [129]:
# MULTIPLICACIÓN

np.array([[1,2],[3,4]])* np.array([[5],[10]])

array([[ 5, 10],
       [30, 40]])

In [131]:
# RESTA

np.array([[1,2],[3,4]])- np.array([[5],[10]])

array([[-4, -3],
       [-7, -6]])

In [135]:
# INDEXACIÓN DE UN SÓLO ELEMENTO

x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
# EXTRACCIÓN DE ELEMENTOS DE FORMA ASCENDENTE

x[2]

2

In [143]:
# EXTRACCIÓN DE ELEMENTOS DE FORMA DESCENDENTE

x[-2]

8

In [145]:
# CONVERSIÓN DE ELEMENTO EN FORMA BIDIMENSIONAL

x.shape=(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [147]:
# EXTRACCIÓN DE ELEMENTO CON ÍNDICE 1 EN RENGLÓ E ÍNDICE 3 EN COLUMNA

x[1,3]

8

In [149]:
# ALTERNATIVA PARA EXTRACCIÓN DE ELEMENTO CON ÍNDICE 1 EN RENGLÓN E ÍNDICE 3 EN COLUMNA

x[1][3]

8

In [151]:
# EXTRACCIÓN DE ELEMENTO CON ÍNDICE 1 EN RENGLÓN Y ELEMENTO 2 EN FORMA DESCENDENTE

x[1,-1]

9

In [153]:
# EXTRACCIÓN DE RENGLON COMPLETO AL NO ESPECIFICAR COLUMNA CON UN SEGUNDO DATO

x[0]

array([0, 1, 2, 3, 4])

In [216]:
# EXTRACCIÓN CON CORTES EN EL ARREGLO

x=np.array([0,1,2,3,4,5,6,7,8,9])
x[1:7:2]

array([1, 3, 5])

In [232]:
x[-1::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [167]:
# EXTRACCIÓN CON CORTES EN EL ARREGLO DE ADELANTE HACIA ATRÁS

x[-2:10]

array([8, 9])

In [171]:
# CORTE DE ARREGLO DE ADELANTE HACIA ATRÁS, INICIANDO 3 POSICIONES A PARTIR DEL FINAL Y RETROCEDIENDO DE 1 EN UNO HASTA LLEGAR AL 4, YA QUE EL LÍMITE ES 3

x[-3:3:-1]

array([7, 6, 5, 4])

In [177]:
# CREACIÓN DE ARREGLO EN FORMA DESCENDENTE DE 10 AL 1 ( SIN INCUIRLO) CON DECREMENTOS DE -1
x= np.arange(10,1,-1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [181]:
# EXTRACCIÓN DE ELEMENTOS ESPECÍFICOS DE UN ARREGLO

x[np.array([3,3,1,8])]

array([7, 7, 9, 2])

In [183]:
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

In [187]:
# EXTRACCIÓN BASADA EN PARES

y=np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [191]:
# EXTRACCIÓN DE CORDENADAS (0,0), (2,1),(4,2)

y[np.array([0,2,2]),np.array([0,1,2])]

array([ 0, 15, 16])

In [193]:
# CONCATENACIÓN DE VECTORES

arr=np.concatenate(([1,2,3],[4,5,6]))
arr

array([1, 2, 3, 4, 5, 6])

In [195]:
# APILADDO VERTICAL DE VECTORES

np.stack(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [201]:
# CONCATENACIÓN DE MATRICES

mat_1=np.array([[1,2,3],[4,5,6]])
mat_2=np.array([[1,1,1],[2,2,2]])

np.concatenate((mat_1,mat_2),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [203]:
np.concatenate((mat_1,mat_2),axis=1)

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

In [205]:
np.concatenate((mat_1,mat_2),axis=None)

array([1, 2, 3, 4, 5, 6, 1, 1, 1, 2, 2, 2])